---
abstract: 'build assistance for Bundle and Task distributions'
author:
  - 'Jonas B. Nielsen (jonasbn), <jonasbn@cpan.org>'
configure_requires:
  Module::Build: 0.36
generated_by: 'Module::Build version 0.3607'
license: artistic
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Module-Build-Bundle
provides:
  Module::Build::Bundle:
    file: lib/Module/Build/Bundle.pm
    version: 0.03
requires:
  Carp: 0
  Cwd: 0
  English: 0
  File::Copy: 0
  FindBin: 0
  Module::Build::YAML: 0
  Test::Class: 0
  Test::More: 0
  Tie::IxHash: 0
  perl: v5.6.0
resources:
  ProjectChangelog: http://logiclab.jira.com/browse/MBB#selectedTab=com.atlassian.jira.plugin.system.project%3Achangelog-panel
  ProjectSite: http://logicLAB.jira.com/browse/MBB
  ProjectWiki: http://logiclab.jira.com/wiki/display/MBB/Home
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=Module-Build-Bundle
  homepage: http://logiclab.jira.com/wiki/display/MBB/Home
  license: http://www.perlfoundation.org/artistic_license_1_0
  repository: http://logicLAB.jira.com/svn/MBB
version: 0.03
